// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjwebmpvaaeogbfqxwub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhqd2VibXB2YWFlb2diZnF4d3ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MjMyNzAsImV4cCI6MjA2MzA5OTI3MH0.4fKNzbMpsetnc2JAhC5SbzwdCiMFkUSSTJxphlIBiuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);