// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmzntydwfdukiebhlmfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtem50eWR3ZmR1a2llYmhsbWZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MDI0MzksImV4cCI6MjA2MzA3ODQzOX0.e7Ko-Uy0tp1On4oJC8-NrsvvLnWVEVZET3QvN3AGNHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);